In [5]:
from google.colab import files
uploaded=files.upload()

Saving ML - Cleaned.csv to ML - Cleaned (1).csv

In [12]:
from google.colab import files

# Upload your CSV file
uploaded = files.upload()

import pandas as pd

# Read the CSV file
df = pd.read_csv("ML_Cleaned.csv")

# Display the first 5 rows
df.head()

Saving ML - Cleaned.csv to ML - Cleaned.csv

,Inudstry Type,Equipment,Fuel Type,Any CEMS installed? Yes/No.,Rated capacity,Capacity Unit (TPH / MW / kVA / (cal/hr)),Avg hours/day:,Days/Year,Load factor - non DG set (%):,Avg Fuel used per day:(kg/kl/kw),Fuel unit per day (kg/kl),Density conversion factor,APCD Type,PM10(kg/day),PM2.5(kg/day),SO2(kg/day),NO2(kg/day),CO(kg/day),VOC(kg/day),Unnamed: 19
0,Pharma,Boiler,Coal,Yes,4.0,tph,20.00,365.0,80,9.000000,t/day,1.00000,Bag Filter,6.4,5.7,68.4,49.5,2.7,0.035730,NaN
1,Pharma,Boiler,Coal,Yes,6.0,tph,20,365.0,60,9.500000,t/day,1.00000,Bag Filter,6.7,6.0,72.2,52.3,2.9,0.037715,NaN
2,Pharma,Boiler,Diesel/PNG,Yes,0.4,tph,13.00,180.0,75,268.266667,cubic litre/day,0.00085,NaN,0.0,0.0,0.0,0.3,0.1,0.154924,NaN
3,Pharma,Boiler,Coal,Yes,2.0,tph,24.00,365.0,65,2.400000,t/day,1.00000,Cyclone,16.9,61.0,18.2,13.2,0.7,0.009528,NaN
4,Pharma,Boiler,Coal,Yes,1.0,tph,16.00,360.0,80,0.500000,t/day,1.00000,Cyclone,3.5,12.5,3.7,2.7,0.1,0.001958,NaN

In [13]:
df.shape

(270, 20)

In [14]:
df.columns

Index(['Inudstry Type', 'Equipment', 'Fuel Type',
       'Any CEMS installed? Yes/No. ', 'Rated capacity',
       'Capacity Unit (TPH / MW / kVA / (cal/hr))', 'Avg hours/day: ',
       'Days/Year', 'Load factor - non DG set (%):',
       'Avg Fuel used per day:(kg/kl/kw)', 'Fuel unit per day (kg/kl)',
       'Density conversion factor', 'APCD Type', 'PM10(kg/day) ',
       'PM2.5(kg/day) ', 'SO2(kg/day) ', 'NO2(kg/day)', 'CO(kg/day) ',
       'VOC(kg/day)', 'Unnamed: 19'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 20 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Inudstry Type                              270 non-null    object
 1   Equipment                                  270 non-null    object
 2   Fuel Type                                  269 non-null    object
 3   Any CEMS installed? Yes/No.                270 non-null    object
 4   Rated capacity                             268 non-null    float64
 5   Capacity Unit (TPH / MW / kVA / (cal/hr))  268 non-null    object
 6   Avg hours/day:                             261 non-null    object
 7   Days/Year                                  269 non-null    float64
 8   Load factor - non DG set (%):              238 non-null    object
 9   Avg Fuel used per day:(kg/kl/kw)           267 non-null    float64
 10  Fuel unit per day (kg/kl)                  269 non-null    object
 11  Density conversion factor                  82 non-null     float64
 12  APCD Type                                  50 non-null     object
 13  PM10(kg/day)                               270 non-null    float64
 14  PM2.5(kg/day)                              270 non-null    float64
 15  SO2(kg/day)                                270 non-null    float64
 16  NO2(kg/day)                                270 non-null    float64
 17  CO(kg/day)                                 270 non-null    float64
 18  VOC(kg/day)                                268 non-null    float64
 19  Unnamed: 19                                1 non-null      float64
dtypes: float64(11), object(9)
memory usage: 42.3+ KB

In [16]:
df = df.drop(columns=["Unnamed: 19"])

In [17]:
df = df.drop(columns=["Density conversion factor"])

In [18]:
df = df.rename(columns={"Inudstry Type": "Industry Type"})

In [19]:
df["APCD Type"] = df["APCD Type"].fillna("Unknown")

In [20]:
print(df["Avg hours/day: "].unique())
print(df["Load factor - non DG set (%):"].unique())

['20.00' '20' '13.00' '24.00' '16.00' nan '4' '8.00' '12.00' '8.5 mins'
 '15h' '16-18' '46117.00' '21.00' '4.00' '2.00' '24' '22' '8' '2' '12'
 '0.5' '0.111111111' '0.291666667' '0.333333333' '0.15' '0.166666667'
 '0.2' '1.5' '1' '0.133333333' '0.375' '0.433333333' '0.1' '0.266666667'
 '0.25' '0.05' '0.42' '0.17' '0.666666667' '0.233333333' '0.183333333'
 '0.833333333' '3' '0.283333333' '0.366666667' '0.4' '1.666666667'
 '0.066666667' '1.416666667' '0.8' '0.733333333' '0' '0.416666667'
 '0.277666667' '0.277777778' '1.033333333' '0.29' '0.23' '7' '6' '4.5'
 '15' '13']
['80' '60' '75' '65' '70' '50' '90' '40' '75-80' '100' nan '40%' '75%'
 '40-50' '75-90' '35%' '60%' '0.65' '30' '50-55' '20' '50-60' '67.5'
 '62.5' '37.5' '25' '86' '0' '65%']

In [21]:
df["Avg hours/day: "] = pd.to_numeric(
    df["Avg hours/day: "], errors="coerce"
)

df["Load factor - non DG set (%):"] = pd.to_numeric(
    df["Load factor - non DG set (%):"], errors="coerce"
)

In [22]:
# Numeric columns
numeric_cols = [
    "Rated capacity",
    "Avg hours/day: ",
    "Days/Year",
    "Load factor - non DG set (%):",
    "Avg Fuel used per day:(kg/kl/kw)",
    "VOC(kg/day)"
]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns
categorical_cols = [
    "Fuel Type",
    "Capacity Unit (TPH / MW / kVA / (cal/hr))",
    "Fuel unit per day (kg/kl)",
    "APCD Type",
    "Any CEMS installed? Yes/No. "
]

for col in categorical_cols:
    if col == "APCD Type":
        df[col] = df[col].fillna("Unknown")
    else:
        df[col] = df[col].fillna(df[col].mode()[0])

In [23]:
df.isnull().sum()

Industry Type                                0
Equipment                                    0
Fuel Type                                    0
Any CEMS installed? Yes/No.                  0
Rated capacity                               0
Capacity Unit (TPH / MW / kVA / (cal/hr))    0
Avg hours/day:                               0
Days/Year                                    0
Load factor - non DG set (%):                0
Avg Fuel used per day:(kg/kl/kw)             0
Fuel unit per day (kg/kl)                    0
APCD Type                                    0
PM10(kg/day)                                 0
PM2.5(kg/day)                                0
SO2(kg/day)                                  0
NO2(kg/day)                                  0
CO(kg/day)                                   0
VOC(kg/day)                                  0
dtype: int64

In [24]:
print(df.columns.tolist())

['Industry Type', 'Equipment', 'Fuel Type', 'Any CEMS installed? Yes/No. ', 'Rated capacity', 'Capacity Unit (TPH / MW / kVA / (cal/hr))', 'Avg hours/day: ', 'Days/Year', 'Load factor - non DG set (%):', 'Avg Fuel used per day:(kg/kl/kw)', 'Fuel unit per day (kg/kl)', 'APCD Type', 'PM10(kg/day) ', 'PM2.5(kg/day) ', 'SO2(kg/day) ', 'NO2(kg/day)', 'CO(kg/day) ', 'VOC(kg/day)']

In [25]:
df.columns = df.columns.str.strip()

In [26]:
print(df.columns.tolist())

['Industry Type', 'Equipment', 'Fuel Type', 'Any CEMS installed? Yes/No.', 'Rated capacity', 'Capacity Unit (TPH / MW / kVA / (cal/hr))', 'Avg hours/day:', 'Days/Year', 'Load factor - non DG set (%):', 'Avg Fuel used per day:(kg/kl/kw)', 'Fuel unit per day (kg/kl)', 'APCD Type', 'PM10(kg/day)', 'PM2.5(kg/day)', 'SO2(kg/day)', 'NO2(kg/day)', 'CO(kg/day)', 'VOC(kg/day)']

In [27]:
X = df[
    [
        "Industry Type",
        "Equipment",
        "Fuel Type",
        "Any CEMS installed? Yes/No.",
        "Rated capacity",
        "Capacity Unit (TPH / MW / kVA / (cal/hr))",
        "Avg hours/day:",
        "Days/Year",
        "Load factor - non DG set (%):",
        "Avg Fuel used per day:(kg/kl/kw)",
        "Fuel unit per day (kg/kl)",
        "APCD Type"
    ]
]

Y = df[
    [
        "PM10(kg/day)",
        "PM2.5(kg/day)",
        "SO2(kg/day)",
        "NO2(kg/day)",
        "CO(kg/day)",
        "VOC(kg/day)"
    ]
]

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [29]:
categorical_features = [
    "Industry Type",
    "Equipment",
    "Fuel Type",
    "Any CEMS installed? Yes/No.",
    "Capacity Unit (TPH / MW / kVA / (cal/hr))",
    "Fuel unit per day (kg/kl)",
    "APCD Type"
]

numeric_features = [
    "Rated capacity",
    "Avg hours/day:",
    "Days/Year",
    "Load factor - non DG set (%):",
    "Avg Fuel used per day:(kg/kl/kw)"
]

In [30]:
print(X.shape)
print(Y.shape)

print(X_train.shape)
print(X_test.shape)

print(Y_train.shape)
print(Y_test.shape)

(270, 12)
(270, 6)
(216, 12)
(54, 12)
(216, 6)
(54, 6)

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [35]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ],
    remainder="passthrough"
)

In [36]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor

model = MultiOutputRegressor(
    RandomForestRegressor(
        n_estimators=200,
        random_state=42
    )
)

In [37]:
pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", model)
    ]
)

In [38]:
pipeline.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Industry Type', 'Equipment',
                                                   'Fuel Type',
                                                   'Any CEMS installed? '
                                                   'Yes/No.',
                                                   'Capacity Unit (TPH / MW / '
                                                   'kVA / (cal/hr))',
                                                   'Fuel unit per day (kg/kl)',
                                                   'APCD Type'])])),
                ('model',
                 MultiOutputRegressor(estimator=RandomForestRegressor(n_estimators=200,
                                                                      random_state=42)))])

In [39]:
predictions = pipeline.predict(X_test)

In [40]:
predictions[:5]

array([[2.28206918e+02, 2.04581071e+02, 3.05944435e+01, 2.07307584e+01,
        1.00190343e+00, 1.44732184e-02],
       [1.95160226e-02, 1.77202407e-02, 2.70588464e-03, 5.79391853e-01,
        1.79367841e-01, 3.10684048e-02],
       [1.61778116e-02, 1.51349032e-02, 2.10615445e-03, 4.51201107e-01,
        1.32473606e-01, 2.71602699e-02],
       [1.37709055e-02, 1.20832801e-02, 1.85111989e-03, 3.80575595e-01,
        1.25432677e-01, 1.93928248e-02],
       [2.37581630e-02, 2.13969965e-02, 3.38952699e-03, 6.82368441e-01,
        2.08021059e-01, 3.46259649e-02]])

In [41]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [42]:
mae = mean_absolute_error(Y_test, predictions)
rmse = mean_squared_error(Y_test, predictions) ** 0.5
r2 = r2_score(Y_test, predictions)

print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 2.1662635442350555
RMSE: 11.906661954782553
R²  : 0.5524857390981276

In [43]:
import joblib

joblib.dump(pipeline, "pipeline.pkl")

['pipeline.pkl']

In [44]:
from google.colab import files

files.download("pipeline.pkl")

In [45]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test, predictions)
print(r2)

0.5524857390981276

In [46]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(Y_test, predictions)
print(mae)

2.1662635442350555

In [47]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(Y_test, predictions))
print(rmse)

11.906661954782553

In [48]:
for i, col in enumerate(Y.columns):
    score = r2_score(Y_test.iloc[:, i], predictions[:, i])
    print(f"{col}: {score:.3f}")

PM10(kg/day): 0.864
PM2.5(kg/day): 0.765
SO2(kg/day): 0.399
NO2(kg/day): 0.546
CO(kg/day): 0.868
VOC(kg/day): -0.126

In [49]:
comparison = Y_test.copy()
comparison["Pred_PM10"] = predictions[:, 0]
comparison["Pred_PM2.5"] = predictions[:, 1]

comparison.head(10)

,PM10(kg/day),PM2.5(kg/day),SO2(kg/day),NO2(kg/day),CO(kg/day),VOC(kg/day),Pred_PM10,Pred_PM2.5
30,353.000000,317.700000,38.000000,27.500000,1.500000,0.019850,228.206918,204.581071
116,0.022562,0.020342,0.003144,0.658726,0.206014,0.035137,0.019516,0.017720
79,0.021659,0.019529,0.003018,0.632377,0.197773,0.033732,0.016178,0.015135
127,0.015041,0.013562,0.002096,0.439151,0.137342,0.023425,0.013771,0.012083
196,0.018049,0.016274,0.002515,0.526981,0.164811,0.028110,0.023758,0.021397
137,0.004043,0.003645,0.000563,0.118044,0.036918,0.006297,0.004690,0.004362
209,0.010781,0.009721,0.001502,0.314783,0.098447,0.016791,0.009548,0.008681
45,1.800000,1.600000,19.000000,13.800000,0.800000,0.009925,4.001500,6.679500
158,0.001755,0.001582,0.000245,0.051234,0.016023,0.002733,0.001808,0.001673
247,0.011624,0.010480,0.001620,0.339376,0.106138,0.018103,0.011788,0.010536